# Generated by Django 5.2.4 on 2025-12-09 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Package_tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageDetails',
            fields=[
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Package_tracking.package')),
                ('receiver_address', models.TextField(max_length=500)),
                ('package_details', models.TextField(max_length=100)),
                ('package_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
